services:

  kafka:
    image: bitnami/kafka:3.5
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 5s
      retries: 5

  producer:
    build:
      context: ../src/producer
      dockerfile: Dockerfile
    networks:
      - kafka-net
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_BROKERS=kafka:9092
      - TOPIC=test-topic

  consumer:
    build:
      context: ../src/consumer
      dockerfile: Dockerfile
    networks:
      - kafka-net
    depends_on:
      - producer
    environment:
      - KAFKA_BROKERS=kafka:9092
      - TOPIC=test-topic
      - GROUP_ID=my-group

networks:
  kafka-net:
    driver: bridge
